### ISSUE TITLE
Error on addfile: [default-akka.actor.default-dispatcher-4] [akka://default/user/userInteface] Input length = 1

### ISSUE THREAD

**Issue by fho** [rtrlib/rtr-testsuite#1]
When I added the RIB dump I got the following error:

> rtr-testsuite> addfile /home/fho/Downloads/rpki-test-script/rib.20170125.0600
addfile /home/fho/Downloads/rpki-test-script/rib.20170125.0600
> [ERROR] [01/25/2017 08:48:34.395] [default-akka.actor.default-dispatcher-3] [akka://default/user/userInteface] Input length
>  = 1
> akka.actor.ActorInitializationException: exception during creation
>         at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
>         at akka.actor.ActorCell.create(ActorCell.scala:596)
>         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
>         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
>         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: java.nio.charset.MalformedInputException: Input length = 1
>         at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
>         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
>         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
>         at java.io.InputStreamReader.read(InputStreamReader.java:184)
>         at java.io.BufferedReader.fill(BufferedReader.java:161)
>  at java.io.BufferedReader.readLine(BufferedReader.java:324)
>         at java.io.BufferedReader.readLine(BufferedReader.java:389)
>         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
>         at main.scala.RtrPrefixStore.readPrefixesFromFile(RtrPrefixStore.scala:81)
>         at main.scala.RtrPrefixStore.addPrefixesFromFile(RtrPrefixStore.scala:64)
>         at main.scala.UserInterface.executeCommand(UserInterface.scala:124)
>         at main.scala.UserInterface.interactiveShell(UserInterface.scala:27)
>         at main.scala.UserInterface.<init>(UserInterface.scala:12)
>         at main.scala.Main$$anonfun$6.apply(Main.scala:81)
>         at main.scala.Main$$anonfun$6.apply(Main.scala:81)
>         at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343)
>         at akka.actor.Props.newActor(Props.scala:252)
>         at akka.actor.ActorCell.newActor(ActorCell.scala:552)
>         at akka.actor.ActorCell.create(ActorCell.scala:578)
>         ... 9 more

How to reproduce:

- download & extract http://archive.routeviews.org/bgpdata/2017.01/RIBS/rib.20170125.0600.bz2
- download & extract https://github.com/rtrlib/rtr-testsuite/releases/download/0.0.1/RTRTestsuite-0.0.1-SNAPSHOT-dist.tar.gz
- ./rtr-testsuite.sh
- addfile <path-to-extracted-rib>

Java version:

> $ java -version
> openjdk version "1.8.0_121"
> OpenJDK Runtime Environment (build 1.8.0_121-b13)
> OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by reuteran** [comment]
Hey,
the 'addfile' command expects a file with format:
`[ASN] [Prefix] [MaxLen]`
per line. You can verify with 'show' that the file was loaded correctly.
There's no clean error handling as of now, so it just fails if it gets something it doesn't expect (same for other commands).

**Comment by fho** [comment]
ok, thanks! :-)
